// Sample content for the trailer. Every person, account, product and number here is invented.
// v: [action, topic name, confidence shown in the extension's own label]
window.TRAILER_DATA = {
  shards: [
    ["Growth Guru", "Comment “GUIDE” and I’ll DM you my 47-page playbook", "412 replies"],
    ["Hot Takes Daily", "Anyone who disagrees with this is an idiot. Fight me.", "9.2K quote posts"],
    ["Mindset Mentor", "Success is a journey, not a destination. Agree? 👇", "Promoted"],
    ["Breaking Outrage", "You will NOT believe what he just said", "Trending"],
    ["Thread Boi", "10 lessons from my morning routine 🧵 (no. 7 is wild)", "1.1M views"],
    ["Crypto Whale 🚀", "$FROG is about to 100x. Presale ends in 2 hours", "Promoted"],
    ["Humble Harold", "I’m humbled and honored to announce…", "2,340 reactions"],
    ["Chad Winters", "I woke up at 3:47am. Cold plunge. 40 sales calls.", "Suggested"],
    ["REACTS", "REACTING to the WORST code on the internet 😱", "Recommended"],
    ["Giveaway Central", "RT + follow to win. Ends tonight!!!", "38K reposts"],
    ["Bradley Thornton", "I fired my best employee today. Here’s what it taught me about B2B sales", "Suggested"],
    ["Drama Digest", "He said WHAT?! Tech drama EXPLAINED", "Recommended"],
    ["Alpha Daily", "Most people will scroll past this. Winners won’t.", "Promoted"],
    ["Ragewire", "This is what THEY don’t want you to see", "Trending"],
    ["LinkedInfluencer", "My toddler taught me a lesson about enterprise SaaS", "Suggested"],
    ["Clickfarm TV", "This ONE trick made me a 10x developer (not clickbait)", "Recommended"],
    ["Poll Master", "Tabs or spaces? Wrong answers only 👇", "12K replies"],
    ["Doom Desk", "BREAKING: everything is terrible, again", "Trending"],
    ["Sell Bot", "Last chance! 80% OFF my course ends at midnight", "Promoted"],
    ["Vague Poster", "Big things coming. Can’t say more. 👀", "2.4K likes"],
    ["Quote Machine", "“Be the energy you want to attract.”", "Suggested"],
    ["Engage Farm", "Like if you code. Repost if you’re a real developer.", "61K likes"],
    ["Hype Letter", "AI just changed EVERYTHING (again). Here’s how 🧵", "Recommended"],
    ["Outrage Loop", "Ratio this clown", "4.4K replies"],
  ],
  x: [
    { n: "Growth Guru", h: "@10xgrowthguru", tm: "1h", c: "#b4462f", st: ["412", "1.2K", "3.9K", "212K"], v: ["hide", "Engagement bait", 96],
      tx: "I made $47,000 in 30 days with ONE simple system.\n\nComment “GUIDE” and I’ll DM you the 47-page playbook. Must be following." },
    { n: "Maya Okafor", h: "@mayabuilds", tm: "2h", c: "#2f6db4", st: ["38", "21", "402", "18K"], v: ["keep", "Indie building", 97],
      tx: "Shipped v2 of my invoicing app last night.\n\n312 paying customers, $4.1k MRR. Rewriting the pricing page did more than six months of features. Notes in the thread." },
    { n: "Hot Takes Daily", h: "@hottakesdaily", tm: "2h", c: "#8a2fb4", st: ["2.1K", "890", "1.4K", "530K"], v: ["hide", "Rage bait", 93],
      tx: "Anyone still writing tests in 2026 is a dinosaur and frankly should not be allowed near a keyboard. Fight me." },
    { n: "Ravi Menon", h: "@ravicodes", tm: "3h", c: "#2f9c8a", st: ["12", "44", "310", "22K"], v: ["highlight", "Technical depth", 91],
      tx: "TIL Postgres can do a partial unique index, so “one active subscription per user” is one line instead of a trigger. Example below." },
    { n: "Mindset Mentor", h: "@riseandgrind", tm: "3h", c: "#b48a2f", st: ["340", "2.2K", "9.1K", "410K"], v: ["hide", "Generic filler", 95],
      tx: "Success is not final. Failure is not fatal. It is the courage to continue that counts.\n\nAgree? 👇" },
    { n: "Lena Park", h: "@lenaships", tm: "4h", c: "#5b6b7a", st: ["3", "0", "27", "1.1K"], v: null,
      tx: "Coffee, rain, and a bug that only happens on Tuesdays. Good morning." },
    { n: "Crypto Whale 🚀", h: "@moonsignals", tm: "4h", c: "#3f8f3a", st: ["98", "1.9K", "4.4K", "390K"], v: ["hide", "Crypto promotion", 98],
      tx: "$FROG is about to 100x. Devs are doxxed. Presale closes in 2 hours. Don’t say I didn’t warn you. 🚀🚀🚀" },
    { n: "Sam Ortiz", h: "@samortiz_dev", tm: "5h", c: "#b42f5e", st: ["51", "63", "780", "41K"], v: ["keep", "Indie building", 95],
      tx: "Raised my app’s price from $3 to $5 a month. Conversions didn’t move, churn didn’t move, revenue up by half. I waited a year to try this." },
    { n: "Breaking Outrage", h: "@outragewire", tm: "5h", c: "#a33", st: ["5.2K", "11K", "20K", "2.1M"], v: ["dim", "Politics", 88],
      tx: "You will NOT believe what this politician just said about your taxes. Share before it gets deleted!!" },
    { n: "Thread Boi", h: "@threadboi", tm: "6h", c: "#7a5bb4", st: ["77", "640", "2.8K", "160K"], v: ["hide", "Engagement bait", 94],
      tx: "10 lessons from my morning routine that will change your life (number 7 is wild) 🧵" },
    { n: "Noor Haddad", h: "@noorhaddad", tm: "6h", c: "#2f86b4", st: ["29", "8", "512", "9.8K"], v: ["keep", "Indie building", 92],
      tx: "First paying customer from a cold email today. $29. I have never been this happy about $29." },
    { n: "Giveaway Central", h: "@winbigdaily", tm: "7h", c: "#b4702f", st: ["9.9K", "38K", "41K", "3.3M"], v: ["hide", "Engagement bait", 99],
      tx: "RT + follow + tag 3 friends to win a new laptop. Ends tonight!!!" },
    { n: "Alpha Daily", h: "@alphadaily", tm: "7h", c: "#555", st: ["120", "900", "5.1K", "280K"], v: ["hide", "Generic filler", 91],
      tx: "Most people will scroll past this. Winners won’t." },
  ],
  linkedin: [
    { n: "Bradley Thornton", hl: "CEO · Visionary · 3x Founder · Keynote Speaker", c: "#7a4b2f", r: "2,340", v: ["hide", "Hustle sermons", 97],
      tx: "I fired my best employee today.\n\nThen I rehired him at double the salary.\n\nHere’s what it taught me about B2B sales 👇" },
    { n: "Priya Raman", hl: "Engineering Manager at Northwind", c: "#2f6db4", r: "86", v: ["keep", "Hiring", 96],
      tx: "We’re hiring two senior iOS engineers (remote, EU time zones). Small team, real ownership, no whiteboard interviews. Details in the comments." },
    { n: "Chad Winters", hl: "Helping founders 10x · Ex-everything", c: "#8a2f2f", r: "5,112", v: ["hide", "Hustle sermons", 98],
      tx: "I woke up at 3:47am. Cold plunge. 40 sales calls before breakfast.\n\nMy co-founder quit. Best thing that ever happened to my pipeline.\n\nAgree?" },
    { n: "Dana Liu", hl: "Staff Engineer", c: "#2f9c8a", r: "214", v: ["highlight", "Technical depth", 93],
      tx: "Wrote up how we cut CI from 38 minutes to 6. Mostly boring fixes: caching, test sharding, and deleting 400 tests nobody trusted." },
    { n: "Humble Harold", hl: "Thought Leader · Top Voice", c: "#6b5bb4", r: "1,902", v: ["hide", "Hustle sermons", 96],
      tx: "I’m humbled and honored to announce I’ve been named to the Top 40 Most Humble Leaders list. I didn’t want to post this, but…" },
    { n: "Tomás Rivera", hl: "Founder at Fernhill Labs", c: "#2f86b4", r: "57", v: ["keep", "Hiring", 94],
      tx: "Looking for a part-time designer who likes boring B2B software. 10 hours a week, paid trial project, fully async." },
    { n: "Visionary Vince", hl: "Disruptor · Dreamer · Dad", c: "#b4702f", r: "3,480", v: ["hide", "Hustle sermons", 95],
      tx: "My barista spelled my name wrong this morning.\n\nHere are 7 things it taught me about customer success:" },
    { n: "Ines Moreau", hl: "Product Designer", c: "#5b6b7a", r: "41", v: null,
      tx: "Moved our design reviews from meetings to short written notes. Two weeks in, nobody misses the meetings." },
  ],
  youtube: [
    { t: "I Quit My Job and You WON’T BELIEVE What Happened Next", ch: "Hustle Diaries", m: "2.1M views · 3 days ago", d: "14:02", bait: "I QUIT?!", bg: "linear-gradient(135deg,#c1121f,#ff7b00)", c: "#c1121f", v: ["dim", "Clickbait", 95] },
    { t: "How B-trees actually work (database internals, part 3)", ch: "Systems Notebook", m: "48K views · 2 weeks ago", d: "41:17", code: "node.keys = [17, 42]\nsplit(child, mid)\n// O(log n)", bg: "linear-gradient(135deg,#0f2740,#1c4a6e)", c: "#1c4a6e", v: ["highlight", "Deep technical talks", 94] },
    { t: "REACTING to the WORST code on the internet 😱", ch: "CodeReacts", m: "890K views · 1 day ago", d: "22:48", bait: "WORST CODE EVER 😱", bg: "linear-gradient(135deg,#6a00f4,#f20089)", c: "#6a00f4", v: ["dim", "Clickbait", 92] },
    { t: "Building a text editor from scratch in C", ch: "Low Level Lab", m: "112K views · 1 month ago", d: "1:12:30", code: "while (read(fd, &c, 1))\n  editor_insert(c);\nrender();", bg: "linear-gradient(135deg,#14213d,#274060)", c: "#274060", v: ["highlight", "Deep technical talks", 96] },
    { t: "This ONE trick made me a 10x developer (not clickbait)", ch: "DevGrind", m: "1.4M views · 5 days ago", d: "9:59", bait: "10X IN 1 DAY", bg: "linear-gradient(135deg,#ff006e,#ffbe0b)", c: "#ff006e", v: ["dim", "Clickbait", 97] },
    { t: "lo-fi beats to refactor to", ch: "Quiet Compile", m: "320K views · 8 months ago", d: "2:04:11", code: "♪  ♫  ♪", bg: "linear-gradient(135deg,#3a2f4f,#5b4a6e)", c: "#5b4a6e", v: null },
    { t: "He said WHAT?! Tech drama EXPLAINED", ch: "Drama Digest", m: "640K views · 12 hours ago", d: "18:20", bait: "HE SAID WHAT?!", bg: "linear-gradient(135deg,#d00000,#370617)", c: "#d00000", v: ["dim", "Clickbait", 93] },
    { t: "What we learned running SQLite in production", ch: "Small Stack Conf", m: "76K views · 3 weeks ago", d: "34:45", code: "PRAGMA journal_mode=WAL;\nPRAGMA synchronous=NORMAL;", bg: "linear-gradient(135deg,#0b3d2e,#14624a)", c: "#14624a", v: ["highlight", "Deep technical talks", 92] },
    { t: "I tried EVERY AI tool so you don’t have to (shocking)", ch: "Hype Letter TV", m: "2.8M views · 2 days ago", d: "12:12", bait: "SHOCKING RESULTS", bg: "linear-gradient(135deg,#f72585,#7209b7)", c: "#f72585", v: ["dim", "Clickbait", 94] },
  ],
  // what "Test it" returns for the topic typed in the trailer
  testPosts: [
    ["Shipped v2 of my invoicing app last night. 312 paying customers, $4.1k MRR. Notes in the thread.", 0.97],
    ["Raised my app’s price from $3 to $5 a month. Conversions didn’t move, revenue up by half.", 0.95],
    ["First paying customer from a cold email today. $29.", 0.92],
    ["I made $47,000 in 30 days with ONE simple system. Comment GUIDE for the playbook.", 0.31],
    ["Success is not final. Failure is not fatal. Agree?", 0.03],
  ],
};
